spring:
  application:
    name: "monkey"
  profiles.active: "@spring.profiles.active@"
  datasource:
     url: "@datasource.url@"
     driver-class-name: "@datasource.driver@"
     username: "@datasource.username@"
     password: "@datasource.password@"
  jpa:
     show-sql: true
     hibernate.ddl-auto: "@datasource.jpa.ddl-auto@"
     database-platform: "@datasource.dialect@"
  redis:
    host: 117.78.0.112
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1

logging:
  level:
    com.look: trace
    com.querydsl.jpa.impl: debug
    web: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug

server:
  port: 8080
  servlet:
    context-path:

